// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetQuestion():Promise<string>;

export function UserCancelAnswer():Promise<void>;

export function UserSubmitAnswer(arg1:main.UserAnswer):Promise<void>;
