// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQuestion() {
  return window['go']['main']['App']['GetQuestion']();
}

export function UserCancelAnswer() {
  return window['go']['main']['App']['UserCancelAnswer']();
}

export function UserSubmitAnswer(arg1) {
  return window['go']['main']['App']['UserSubmitAnswer'](arg1);
}
